# Inputs for Neural Net
- Type of game played
- Length of game (time and moves)
- Game outcomes
    - Winner
    - Type of outcome
- Move evaluation
    - Variance
    - Mean
    - IQR
    - Next best moves
        - Mean
        - Did they choose the best move?
        - Did they choose the next best move?
- Piece evaluation
    - Number of moves of each piece
    - Captures per piece
    - Number of checks
    - Checks per piece
    - Breakdown per part of the game

# Environment Notes
To get the project to run properly, the python version needs to be set to 3.11. Create a fresh conda envioronment. Run the following commands:
```bash
conda create -n chess python-3.11
conda activate chess
pip install pandas
pip install matplotlib
pip install seaborn
pip install chess
pip install tensorflow
```

In [266]:
# Import Libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import chess

# Loading and Cleaning

In [250]:
# Import data and observe shape and columns
chess_data_raw = pd.read_csv("data/games.csv")
print(chess_data_raw.shape)
print(chess_data_raw.columns)
chess_data_raw.head()

chess_data_raw = chess_data_raw[chess_data_raw['turns'] >= 4]

chess_data = chess_data_raw.drop(columns=["id", "white_id", "black_id"])
chess_data = chess_data.dropna()

# Drop all non-rated games for doing rating analysis
chess_data = chess_data[chess_data["rated"] == True]
# Remove rated, created at, and last move at columns
chess_data = chess_data.drop(["rated","created_at","last_move_at"],axis=1)
# Map winner column
chess_data["winner"] = chess_data["winner"].map({"black": -1, "white": 1}).fillna(0)
# Map victory column
chess_data["victory_status"] = chess_data["victory_status"].map({"resign": 0, "mate": 1,"draw": 2, "outoftime": 3})
# Convert moves column to array of moves
chess_data["moves"] = chess_data["moves"].str.split(" ")
# Add column for average player ELO per game
chess_data["game_rating"] = (chess_data["white_rating"] + chess_data["black_rating"]) / 2
# Add column to bucket games by rating 
chess_data["rating_bucket"] = pd.cut(
    chess_data["game_rating"],
    bins=3,
    labels=["low", "medium", "high"]
)

print(chess_data.shape)
chess_data.head()

(20058, 16)
Index(['id', 'rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='str')
(15943, 12)

,turns,victory_status,winner,increment_code,white_rating,black_rating,moves,opening_eco,opening_name,opening_ply,game_rating,rating_bucket
1,16,0,-1.0,5+10,1322,1261,"[d4, Nc6, e4, e5, f4, f6, dxe5, fxe5, fxe5, Nx...",B00,Nimzowitsch Defense: Kennedy Variation,4,1291.5,low
2,61,1,1.0,5+10,1496,1500,"[e4, e5, d3, d6, Be3, c6, Be2, b5, Nd2, a5, a4...",C20,King's Pawn Game: Leonardis Variation,3,1498.0,medium
3,61,1,1.0,20+0,1439,1454,"[d4, d5, Nf3, Bf5, Nc3, Nf6, Bf4, Ng4, e3, Nc6...",D02,Queen's Pawn Game: Zukertort Variation,3,1446.5,medium
4,95,1,1.0,30+3,1523,1469,"[e4, e5, Nf3, d6, d4, Nc6, d5, Nb4, a3, Na6, N...",C41,Philidor Defense,5,1496.0,medium
6,33,0,1.0,10+0,1520,1423,"[d4, d5, e4, dxe4, Nc3, Nf6, f3, exf3, Nxf3, N...",D00,Blackmar-Diemer Gambit: Pietrowsky Defense,10,1471.5,medium

In [251]:
# -------------------------------------------------------
# Use Python Chess to get parameters for neural net
# -------------------------------------------------------


def board_analysis(movelist):
    piece_lookup = {
        chess.PAWN: "pawn",
        chess.KNIGHT: "knight",
        chess.BISHOP: "bishop",
        chess.ROOK: "rook",
        chess.QUEEN: "queen",
        chess.KING: "king",
    }
    piece_values = {
        chess.PAWN: 1,
        chess.KNIGHT: 3,
        chess.BISHOP: 3,
        chess.ROOK: 5,
        chess.QUEEN: 9,
        chess.KING: 0,
    }
    colors = ["white", "black"]
    categories = [
        "moves",
        "captures",
        "checks",
        "forks",
        "pins",
        "attacks",
        "defenses",
        "center_control_turns",
    ]
    pieces = ["pawn", "knight", "bishop", "rook", "queen", "king"]
    center_squares = [chess.D4, chess.E4, chess.D5, chess.E5]

    analysis = {
        color: {
            category: {piece: 0 for piece in pieces}
            for category in categories
        }
        for color in colors
    }
    promotion_counts = {color: 0 for color in colors}
    forced_move_counts = {color: 0 for color in colors}
    material_taken = {color: 0 for color in colors}
    material_lost = {color: 0 for color in colors}

    board = chess.Board()

    for san in movelist:
        try:
            move = board.parse_san(san)
        except Exception:
            break

        color = "white" if board.turn == chess.WHITE else "black"
        opponent_color = "black" if color == "white" else "white"
        piece = board.piece_at(move.from_square)

        if piece is None:
            break

        piece_name = piece_lookup[piece.piece_type]
        analysis[color]["moves"][piece_name] += 1

        captured_value = 0
        if board.is_capture(move):
            analysis[color]["captures"][piece_name] += 1
            if board.is_en_passant(move):
                captured_value = piece_values[chess.PAWN]
            else:
                captured_piece = board.piece_at(move.to_square)
                if captured_piece is not None:
                    captured_value = piece_values[captured_piece.piece_type]

        material_taken[color] += captured_value
        material_lost[opponent_color] += captured_value

        board.push(move)

        if board.is_check():
            analysis[color]["checks"][piece_name] += 1

        attacked_enemy_pieces = 0
        defended_friendly_pieces = 0
        pinned_enemy_pieces = 0
        for square in board.attacks(move.to_square):
            target_piece = board.piece_at(square)
            if target_piece is None:
                continue
            if target_piece.color != piece.color:
                attacked_enemy_pieces += 1
                if board.is_pinned(target_piece.color, square):
                    pinned_enemy_pieces += 1
            else:
                defended_friendly_pieces += 1

        analysis[color]["attacks"][piece_name] += attacked_enemy_pieces
        analysis[color]["defenses"][piece_name] += defended_friendly_pieces

        if attacked_enemy_pieces >= 2:
            analysis[color]["forks"][piece_name] += 1

        if pinned_enemy_pieces > 0:
            analysis[color]["pins"][piece_name] += pinned_enemy_pieces

        if move.promotion is not None:
            promotion_counts[color] += 1

        if board.legal_moves.count() == 1:
            forced_move_counts[color] += 1

        for square in center_squares:
            center_piece = board.piece_at(square)
            if center_piece is None:
                continue
            center_color = "white" if center_piece.color == chess.WHITE else "black"
            center_piece_name = piece_lookup[center_piece.piece_type]
            analysis[center_color]["center_control_turns"][center_piece_name] += 1

    flattened_vector = []
    for color in colors:
        for category in categories:
            for piece in pieces:
                flattened_vector.append(analysis[color][category][piece])

    for color in colors:
        flattened_vector.extend([
            promotion_counts[color],
            forced_move_counts[color],
            material_taken[color],
            material_lost[color],
        ])

    return flattened_vector

In [252]:
colors = ["white", "black"]
categories = [
    "moves",
    "captures",
    "checks",
    "forks",
    "pins",
    "attacks",
    "defenses",
    "center_control_turns",
]
pieces = ["pawn", "knight", "bishop", "rook", "queen", "king"]
summary_metrics = ["promotions", "forced_moves", "material_taken", "material_lost"]

neural_net_columns = [
    f"{color}_{category}_{piece}"
    for color in colors
    for category in categories
    for piece in pieces
] + [
    f"{color}_{metric}"
    for color in colors
    for metric in summary_metrics
]

neural_net_columns += [
    "white_elo",
    "black_elo",
    "winner",
    "total_turns",
    "white_turns",
    "black_turns",
    "idx"
]

neural_net_rows = []

for idx, row in chess_data.iterrows():
    total_turns = row["turns"]
    white_turns = (total_turns + 1) // 2
    black_turns = total_turns // 2

    board_analysis_row = board_analysis(row["moves"])
    board_analysis_row += [
        row["white_rating"],
        row["black_rating"],
        row["winner"],
        total_turns,
        white_turns,
        black_turns,
        idx
    ]
    neural_net_rows.append(board_analysis_row)

neural_net_input = pd.DataFrame(neural_net_rows, columns=neural_net_columns)
neural_net_input.describe()

,white_moves_pawn,white_moves_knight,white_moves_bishop,white_moves_rook,white_moves_queen,white_moves_king,white_captures_pawn,white_captures_knight,white_captures_bishop,white_captures_rook,...,black_forced_moves,black_material_taken,black_material_lost,white_elo,black_elo,winner,total_turns,white_turns,black_turns,idx
count,15943.000000,15943.00000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000,...,15943.000000,15943.000000,15943.000000,15943.00000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000,15943.000000
mean,8.607288,5.57831,4.966067,4.442828,4.010977,4.032052,1.841247,1.363984,1.430095,1.172803,...,0.353008,20.199272,20.374020,1599.90949,1596.395660,0.041147,62.756758,31.637521,31.119237,10121.965502
std,4.381908,3.43769,3.048665,5.252713,3.749370,5.677335,1.375202,1.241930,1.195479,1.490381,...,0.908748,11.310281,11.261918,282.71278,287.500823,0.976612,33.240935,16.615902,16.628786,5789.764497
min,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,784.00000,789.000000,-1.000000,4.000000,2.000000,2.000000,1.000000
25%,5.000000,3.00000,3.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000,0.000000,...,0.000000,11.000000,11.000000,1399.00000,1393.000000,-1.000000,39.000000,20.000000,19.000000,5159.500000
50%,8.000000,5.00000,4.000000,3.000000,3.000000,2.000000,2.000000,1.000000,1.000000,1.000000,...,0.000000,20.000000,20.000000,1579.00000,1576.000000,0.000000,57.000000,29.000000,28.000000,10047.000000
75%,11.000000,7.00000,6.000000,6.000000,5.000000,5.000000,3.000000,2.000000,2.000000,2.000000,...,0.000000,29.000000,30.000000,1795.00000,1793.000000,1.000000,81.000000,41.000000,40.000000,15223.500000
max,35.000000,59.00000,44.000000,83.000000,41.000000,74.000000,8.000000,11.000000,11.000000,9.000000,...,16.000000,55.000000,55.000000,2622.00000,2588.000000,1.000000,349.000000,175.000000,174.000000,20057.000000

In [253]:
neural_net_input

,white_moves_pawn,white_moves_knight,white_moves_bishop,white_moves_rook,white_moves_queen,white_moves_king,white_captures_pawn,white_captures_knight,white_captures_bishop,white_captures_rook,...,black_forced_moves,black_material_taken,black_material_lost,white_elo,black_elo,winner,total_turns,white_turns,black_turns,idx
0,6,0,0,0,2,0,2,0,0,0,...,0,11,2,1322,1261,-1.0,16,8,8,1
1,12,3,8,5,3,0,7,1,3,3,...,0,7,38,1496,1500,1.0,61,31,30,2
2,4,9,4,3,10,1,1,3,2,0,...,0,8,30,1439,1454,1.0,61,31,30,3
3,13,8,3,16,4,4,1,3,1,5,...,1,30,38,1523,1469,1.0,95,48,47,4
4,3,4,5,0,4,1,0,2,0,0,...,0,9,9,1520,1423,1.0,33,17,16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15938,3,4,3,1,0,1,0,1,1,0,...,0,4,2,1691,1220,1.0,24,12,12,20053
15939,8,11,3,2,8,9,2,3,0,0,...,1,26,25,1233,1196,-1.0,82,41,41,20054
15940,3,6,5,0,4,0,0,0,2,0,...,0,6,4,1219,1286,1.0,35,18,17,20055
15941,24,10,4,9,2,6,5,3,2,2,...,2,31,38,1360,1227,1.0,109,55,54,20056
15942,12,3,6,1,8,9,2,1,3,0,...,1,26,22,1235,1339,-1.0,78,39,39,20057

# Nueral Network Development and Design
- Experiment with multiple types of models
- Use smaller data to test
- Find which performs the best
- Train the best performing model using large data

## Import Tensorflow and Relevant Libraries
- Using tensorflow because it is flexible and fast
- It will allow us to process the relatively large dataset (13k rows)

In [254]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Strategy Statistics Model
- Inputs:
    - Action counters (checks, forks, pins, attacks, defenses, moves, and center-control turns per piece per color)
    - Game-level counters (promotions, forced moves, and material taken/lost per color)
    - No centipawn data

- Question: Can ELO be predicted without stockfish centipawn calculation and purely based off of board state and piece statistics?

In [255]:
# ==============================
# Seperate data into X and y
# ==============================

neural_net_input["game_elo"] = neural_net_input[["white_elo", "black_elo"]].mean(axis=1)

feature_cols = [col for col in neural_net_input.columns if col not in ["white_elo", "black_elo", "game_elo"]]
target_cols = ["game_elo"]

X = neural_net_input[feature_cols].values.astype(np.float32)
y = neural_net_input[target_cols].values.astype(np.float32)

# ============================================================
# Split data into test, train, and validation
# ============================================================

X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.15, random_state=42
)

# ===================================
# Create normalization layer (scaling)
# ===================================

normalizer = layers.Normalization(axis=-1)
normalizer.adapt(X_train)

# ==============================
# Build model
# ==============================
model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),
    normalizer,
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])


model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=[keras.metrics.MeanAbsoluteError()]
)

callbacks = [
    keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=15,
        restore_best_weights=True
    )
]

# ==============================
# Train
# ==============================
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=200,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

# ==============================
# Evaluate
# ==============================
pred = model.predict(X_test, verbose=0)

game_mae = mean_absolute_error(y_test[:, 0], pred[:, 0])
game_rmse = np.sqrt(mean_squared_error(y_test[:, 0], pred[:, 0]))

print(f"Game ELO MAE:  {game_mae:.2f}")
print(f"Game ELO RMSE: {game_rmse:.2f}")

Epoch 1/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 666us/step - loss: 882519.0000 - mean_absolute_error: 747.3882 - val_loss: 163420.5000 - val_mean_absolute_error: 319.8758
Epoch 2/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 116911.1562 - mean_absolute_error: 268.1515 - val_loss: 110995.3828 - val_mean_absolute_error: 260.4337
Epoch 3/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - loss: 90242.7344 - mean_absolute_error: 235.7446 - val_loss: 95095.2109 - val_mean_absolute_error: 241.5401
Epoch 4/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 79243.3828 - mean_absolute_error: 221.6550 - val_loss: 86418.3906 - val_mean_absolute_error: 230.4464
Epoch 5/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - loss: 72405.1016 - mean_absolute_error: 212.5496 - val_loss: 80490.6094 - val_mean_absolute_error: 222.6328
Epoch 6/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - loss: 67476.6250 - mean_absolute_error: 205.7114 - val_loss: 76155.8438 - val_mean_absolute_error: 216.9381
Epoch 7/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - loss: 63884.6406 - mean_absolute_error: 200.4566 - val_loss: 73181.3281 - val_mean_absolute_error: 213.0060
Epoch 8/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - loss: 61202.8906 - mean_absolute_error: 196.2835 - val_loss: 71054.8672 - val_mean_absolute_error: 210.2769
Epoch 9/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - loss: 59191.8867 - mean_absolute_error: 193.0560 - val_loss: 69531.0391 - val_mean_absolute_error: 208.3299
Epoch 10/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 57648.9688 - mean_absolute_error: 190.5479 - val_loss: 68316.1250 - val_mean_absolute_error: 206.6908
Epoch 11/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step - loss: 56378.6094 - mean_absolute_error: 188.4605 - val_loss: 67357.2734 - val_mean_absolute_error: 205.3695
Epoch 12/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - loss: 55322.5312 - mean_absolute_error: 186.6672 - val_loss: 66589.2344 - val_mean_absolute_error: 204.3269
Epoch 13/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - loss: 54451.5273 - mean_absolute_error: 185.2001 - val_loss: 66122.5547 - val_mean_absolute_error: 203.6635
Epoch 14/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 53686.4922 - mean_absolute_error: 183.9162 - val_loss: 65713.0156 - val_mean_absolute_error: 203.0226
Epoch 15/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 53008.5312 - mean_absolute_error: 182.7659 - val_loss: 65406.5156 - val_mean_absolute_error: 202.6158
Epoch 16/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 52378.5820 - mean_absolute_error: 181.6803 - val_loss: 65183.9648 - val_mean_absolute_error: 202.2652
Epoch 17/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 51815.9219 - mean_absolute_error: 180.7012 - val_loss: 64956.1992 - val_mean_absolute_error: 201.9435
Epoch 18/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 51258.2305 - mean_absolute_error: 179.7056 - val_loss: 64799.0898 - val_mean_absolute_error: 201.6837
Epoch 19/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 50705.2422 - mean_absolute_error: 178.7085 - val_loss: 64605.4180 - val_mean_absolute_error: 201.4272
Epoch 20/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - loss: 50163.5195 - mean_absolute_error: 177.7277 - val_loss: 64472.1016 - val_mean_absolute_error: 201.2224
Epoch 21/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 49629.8438 - mean_absolute_error: 176.7258 - val_loss: 64315.8242 - val_mean_absolute_error: 200.9591
Epoch 22/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 49103.9805 - mean_absolute_error: 175.7481 - val_loss: 64192.8672 - val_mean_absolute_error: 200.7653
Epoch 23/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 48591.5430 - mean_absolute_error: 174.7908 - val_loss: 64121.6680 - val_mean_absolute_error: 200.5490
Epoch 24/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 48054.1250 - mean_absolute_error: 173.7654 - val_loss: 63987.0547 - val_mean_absolute_error: 200.3559
Epoch 25/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - loss: 47552.2266 - mean_absolute_error: 172.7930 - val_loss: 63939.9570 - val_mean_absolute_error: 200.2484
Epoch 26/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - loss: 47027.1211 - mean_absolute_error: 171.7841 - val_loss: 63926.7891 - val_mean_absolute_error: 200.1949
Epoch 27/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - loss: 46510.7656 - mean_absolute_error: 170.8102 - val_loss: 63930.4180 - val_mean_absolute_error: 200.1444
Epoch 28/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 46004.5352 - mean_absolute_error: 169.8258 - val_loss: 63982.3438 - val_mean_absolute_error: 200.1759
Epoch 29/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - loss: 45480.6016 - mean_absolute_error: 168.7949 - val_loss: 64089.0898 - val_mean_absolute_error: 200.3474
Epoch 30/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 44962.0625 - mean_absolute_error: 167.7872 - val_loss: 64147.2656 - val_mean_absolute_error: 200.4409
Epoch 31/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - loss: 44434.3047 - mean_absolute_error: 166.7068 - val_loss: 64228.1992 - val_mean_absolute_error: 200.5454
Epoch 32/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - loss: 43901.1680 - mean_absolute_error: 165.6234 - val_loss: 64362.7227 - val_mean_absolute_error: 200.7505
Epoch 33/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 43350.5586 - mean_absolute_error: 164.5054 - val_loss: 64556.1797 - val_mean_absolute_error: 201.0986
Epoch 34/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 42801.8828 - mean_absolute_error: 163.3736 - val_loss: 64827.6602 - val_mean_absolute_error: 201.5024
Epoch 35/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - loss: 42250.2070 - mean_absolute_error: 162.2066 - val_loss: 65025.8945 - val_mean_absolute_error: 201.7069
Epoch 36/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - loss: 41714.0820 - mean_absolute_error: 161.0952 - val_loss: 65314.4023 - val_mean_absolute_error: 202.1908
Epoch 37/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - loss: 41195.2852 - mean_absolute_error: 160.0173 - val_loss: 65691.6328 - val_mean_absolute_error: 202.6711
Epoch 38/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - loss: 40693.8242 - mean_absolute_error: 158.9247 - val_loss: 66037.4062 - val_mean_absolute_error: 203.2026
Epoch 39/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 40168.4414 - mean_absolute_error: 157.7744 - val_loss: 66440.3906 - val_mean_absolute_error: 203.8307
Epoch 40/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 39670.1914 - mean_absolute_error: 156.6849 - val_loss: 66827.8828 - val_mean_absolute_error: 204.2903
Epoch 41/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - loss: 39167.6719 - mean_absolute_error: 155.6040 - val_loss: 67122.0781 - val_mean_absolute_error: 204.8168
Game ELO MAE:  190.96
Game ELO RMSE: 242.16

# Analysis
This model performed quite poorly. The mean error was over 200, which is not ideal for ELO. ELO ranges from around 100 - ~3400. The middle 50% of players in this dataset are within 1400 - 1800. This means that our error is too large to accurately guess ELO.

Conclusion: ELO cannot be accurately guessed purely by the strategy statistics calculated for the model. ...

# Neural Net Using Buckets Instead of Regression
- Buckets for classification are high, medium, and low ELO
- Low: <1400
- Medium: 1400-1800
- High: >1800

In [256]:
# ==============================
# Create logical rating buckets
# ==============================
from sklearn.metrics import accuracy_score, classification_report

neural_net_input["average_elo"] = neural_net_input[["white_elo", "black_elo"]].mean(axis=1)
bucket_bins = [0, 1400, 1800, np.inf]
bucket_labels = ["low", "medium", "high"]
neural_net_input["rating_bucket"] = pd.cut(
    neural_net_input["average_elo"],
    bins=bucket_bins,
    labels=bucket_labels,
    include_lowest=True,
    right=False
)

# ==============================
# Prepare bucket classification data
# ==============================
bucket_feature_cols = [
    col for col in neural_net_input.columns
    if col not in ["white_elo", "black_elo", "average_elo", "rating_bucket"]
]
bucket_to_int = {label: idx for idx, label in enumerate(bucket_labels)}

X_bucket = neural_net_input[bucket_feature_cols].values.astype(np.float32)
y_bucket = neural_net_input["rating_bucket"].map(bucket_to_int).astype(np.int32).values

X_bucket_train_full, X_bucket_test, y_bucket_train_full, y_bucket_test = train_test_split(
    X_bucket, y_bucket, test_size=0.15, random_state=42, stratify=y_bucket
)

X_bucket_train, X_bucket_val, y_bucket_train, y_bucket_val = train_test_split(
    X_bucket_train_full,
    y_bucket_train_full,
    test_size=0.15,
    random_state=42,
    stratify=y_bucket_train_full
)

# ===================================
# Create normalization layer (scaling)
# ===================================
bucket_normalizer = layers.Normalization(axis=-1)
bucket_normalizer.adapt(X_bucket_train)

# ==============================
# Build bucket classifier
# ==============================
bucket_model = keras.Sequential([
    keras.Input(shape=(X_bucket_train.shape[1],)),
    bucket_normalizer,
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(len(bucket_labels), activation='softmax')
])

bucket_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

bucket_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=15,
        restore_best_weights=True
    )
]

bucket_history = bucket_model.fit(
    X_bucket_train, y_bucket_train,
    validation_data=(X_bucket_val, y_bucket_val),
    epochs=200,
    batch_size=32,
    callbacks=bucket_callbacks,
    verbose=1
)

bucket_pred_probs = bucket_model.predict(X_bucket_test, verbose=0)
bucket_pred = np.argmax(bucket_pred_probs, axis=1)
bucket_accuracy = accuracy_score(y_bucket_test, bucket_pred)

print(f"Bucket accuracy: {bucket_accuracy:.3f}")
print(classification_report(y_bucket_test, bucket_pred, target_names=bucket_labels))

Epoch 1/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - accuracy: 0.7581 - loss: 0.5408 - val_accuracy: 0.9046 - val_loss: 0.2175
Epoch 2/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.9226 - loss: 0.1867 - val_accuracy: 0.9257 - val_loss: 0.1700
Epoch 3/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9528 - loss: 0.1162 - val_accuracy: 0.9410 - val_loss: 0.1563
Epoch 4/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.9677 - loss: 0.0851 - val_accuracy: 0.9336 - val_loss: 0.1645
Epoch 5/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.9714 - loss: 0.0787 - val_accuracy: 0.9415 - val_loss: 0.1669
Epoch 6/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9743 - loss: 0.0645 - val_accuracy: 0.9297 - val_loss: 0.1991
Epoch 7/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9812 - loss: 0.0498 - val_accuracy: 0.9326 - val_loss: 0.2134
Epoch 8/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.9832 - loss: 0.0462 - val_accuracy: 0.9385 - val_loss: 0.1858
Epoch 9/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9917 - loss: 0.0273 - val_accuracy: 0.9380 - val_loss: 0.2014
Epoch 10/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.9886 - loss: 0.0308 - val_accuracy: 0.9395 - val_loss: 0.2193
Epoch 11/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.9872 - loss: 0.0346 - val_accuracy: 0.9365 - val_loss: 0.2294
Epoch 12/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9857 - loss: 0.0399 - val_accuracy: 0.9341 - val_loss: 0.2409
Epoch 13/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.9870 - loss: 0.0364 - val_accuracy: 0.9415 - val_loss: 0.2260
Epoch 14/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.9912 - loss: 0.0254 - val_accuracy: 0.9282 - val_loss: 0.2983
Epoch 15/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.9914 - loss: 0.0242 - val_accuracy: 0.9326 - val_loss: 0.2976
Epoch 16/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.9922 - loss: 0.0214 - val_accuracy: 0.9311 - val_loss: 0.3019
Epoch 17/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9892 - loss: 0.0290 - val_accuracy: 0.9213 - val_loss: 0.3924
Epoch 18/200
360/360 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.9922 - loss: 0.0210 - val_accuracy: 0.9365 - val_loss: 0.2905
Bucket accuracy: 0.935
              precision    recall  f1-score   support

         low       0.91      0.93      0.92       570
      medium       0.94      0.94      0.94      1272
        high       0.95      0.94      0.94       550

    accuracy                           0.94      2392
   macro avg       0.93      0.93      0.93      2392
weighted avg       0.94      0.94      0.94      2392

# Centipawn Model
- Data processing
- Neural network

In [257]:
import ast

# ==============================
# Data processing
# ==============================

centipawn_data = pd.read_csv("centipawn/centipawn_data_depth_12.csv")

# Clamp values (stockfish provided very high values 100000 and -100000 when checkmate was soon)
centipawn_data["centipawn"] = centipawn_data["centipawn"].apply(ast.literal_eval)
centipawn_data["centipawn"] = centipawn_data["centipawn"].apply(
    lambda values: [max(-1000, min(1000, value)) for value in values]
)

# Sort centipawn by color
centipawn_data["white_centipawn"] = centipawn_data["centipawn"].apply(lambda x: x[::2])
centipawn_data["black_centipawn"] = centipawn_data["centipawn"].apply(lambda x: x[1::2])

# Combine centipawn data with board-analysis features using the explicit index columns
neural_net_with_centipawn = neural_net_input.merge(
    centipawn_data,
    left_on="idx",
    right_on="index",
    how="inner"
)

centipawn_vector_input = neural_net_with_centipawn[neural_net_with_centipawn["total_turns"] >= 40]

centipawn_vector_input = centipawn_vector_input[["white_centipawn", "black_centipawn", "white_elo", "black_elo"]].copy()
centipawn_vector_input["game_elo"] = centipawn_vector_input[["white_elo", "black_elo"]].mean(axis=1)
centipawn_vector_input

,white_centipawn,black_centipawn,white_elo,black_elo,game_elo
1,"[39, 42, 25, 18, 70, 73, 260, 506, 571, 552, 5...","[-38, 15, -6, -14, -46, -84, -268, -504, -530,...",1496,1500,1498.0
2,"[43, 37, 48, 0, 89, 133, 172, 232, 382, 437, 5...","[-34, -32, 13, -5, -69, -70, -105, -199, -262,...",1439,1454,1446.5
3,"[40, 45, 74, 91, 117, 115, 111, 82, 45, -75, -...","[-45, -43, -72, -88, -118, -115, -82, -43, 55,...",1523,1469,1496.0
5,"[47, 46, 32, 114, 53, 51, 44, 15, 10, 1, -24, ...","[-47, 12, -33, -58, -51, -41, -14, -2, -3, 21,...",1439,1392,1415.5
6,"[36, 76, 82, 89, 180, 175, 59, 159, 184, 106, ...","[-47, -73, -81, -92, -184, -66, -55, -153, -77...",1381,1209,1295.0
...,...,...,...,...,...
15934,"[41, 60, 40, 85, 54, 51, 19, 39, -4, -74, -88,...","[-36, -40, -6, -44, -30, -25, -19, 22, 87, 84,...",1328,1252,1290.0
15936,"[43, 59, 38, 7, -189, 22, -271, -350, -159, -1...","[-38, -35, 13, 254, 181, 277, 324, 442, 184, 3...",1237,1231,1234.0
15939,"[43, 64, 132, 111, 8, 23, 15, 18, 21, -28, 82,...","[-43, -48, 2, -9, -2, -4, -17, -15, 74, 22, 26...",1233,1196,1214.5
15941,"[42, 61, 66, -123, -121, -45, -62, -122, -154,...","[-40, -69, 120, 119, 130, 93, 120, 142, 213, 2...",1360,1227,1293.5
15942,"[42, 41, 89, 93, 93, 115, 252, 211, 236, 293, ...","[-40, -22, -94, -77, -87, -102, -169, -169, -2...",1235,1339,1287.0

In [258]:
# ==============================
# Flatten first 20 centipawn moves per side
# ==============================
centipawn_vector_input = centipawn_vector_input[
    (centipawn_vector_input["white_centipawn"].apply(len) >= 20) &
    (centipawn_vector_input["black_centipawn"].apply(len) >= 20)
].copy()

white_cp_columns = [f"white_move_{i + 1}" for i in range(20)]
black_cp_columns = [f"black_move_{i + 1}" for i in range(20)]

white_cp_df = pd.DataFrame(
    centipawn_vector_input["white_centipawn"].apply(lambda moves: moves[:20]).tolist(),
    columns=white_cp_columns,
    index=centipawn_vector_input.index
)

black_cp_df = pd.DataFrame(
    centipawn_vector_input["black_centipawn"].apply(lambda moves: moves[:20]).tolist(),
    columns=black_cp_columns,
    index=centipawn_vector_input.index
)

centipawn_flat_input = pd.concat(
    [
        white_cp_df,
        black_cp_df,
        centipawn_vector_input[["game_elo"]]
    ],
    axis=1
)

centipawn_flat_input.head()

# ==============================
# Prepare data for dense neural net
# ==============================
cp_feature_cols = white_cp_columns + black_cp_columns
cp_target_cols = ["game_elo"]

X_cp = centipawn_flat_input[cp_feature_cols].values.astype(np.float32)
y_cp = centipawn_flat_input[cp_target_cols].values.astype(np.float32)

X_cp_train_full, X_cp_test, y_cp_train_full, y_cp_test = train_test_split(
    X_cp, y_cp, test_size=0.15, random_state=42
)

X_cp_train, X_cp_val, y_cp_train, y_cp_val = train_test_split(
    X_cp_train_full, y_cp_train_full, test_size=0.15, random_state=42
)

# ===================================
# Create normalization layer (scaling)
# ===================================
cp_normalizer = layers.Normalization(axis=-1)
cp_normalizer.adapt(X_cp_train)

# ==============================
# Build dense centipawn model
# ==============================
cp_model = keras.Sequential([
    keras.Input(shape=(40,)),
    cp_normalizer,
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.1),
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(1)
])

cp_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    loss="mse",
    metrics=[keras.metrics.MeanAbsoluteError()]
)

cp_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=30,
        restore_best_weights=True
    )
]

cp_history = cp_model.fit(
    X_cp_train, y_cp_train,
    validation_data=(X_cp_val, y_cp_val),
    epochs=200,
    batch_size=32,
    callbacks=cp_callbacks,
    verbose=1
)

# ==============================
# Evaluate
# ==============================
cp_pred = cp_model.predict(X_cp_test, verbose=0)

cp_game_mae = mean_absolute_error(y_cp_test[:, 0], cp_pred[:, 0])
cp_game_rmse = np.sqrt(mean_squared_error(y_cp_test[:, 0], cp_pred[:, 0]))

print(f"Game ELO MAE:  {cp_game_mae:.2f}")
print(f"Game ELO RMSE: {cp_game_rmse:.2f}")

Epoch 1/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - loss: 1828853.7500 - mean_absolute_error: 1249.8488 - val_loss: 1067928.7500 - val_mean_absolute_error: 895.3959
Epoch 2/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 777290.7500 - mean_absolute_error: 747.5193 - val_loss: 468286.1562 - val_mean_absolute_error: 564.4819
Epoch 3/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - loss: 282107.9062 - mean_absolute_error: 422.0841 - val_loss: 165290.4844 - val_mean_absolute_error: 312.4846
Epoch 4/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 130710.7578 - mean_absolute_error: 280.5849 - val_loss: 104583.8828 - val_mean_absolute_error: 249.8507
Epoch 5/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 94829.8203 - mean_absolute_error: 240.9922 - val_loss: 83313.5781 - val_mean_absolute_error: 224.9286
Epoch 6/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 77302.8047 - mean_absolute_error: 219.4095 - val_loss: 70256.8984 - val_mean_absolute_error: 208.6019
Epoch 7/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 67113.9141 - mean_absolute_error: 204.8925 - val_loss: 62350.0977 - val_mean_absolute_error: 198.0652
Epoch 8/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 59932.3359 - mean_absolute_error: 194.9654 - val_loss: 56968.5625 - val_mean_absolute_error: 190.4994
Epoch 9/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 55505.8633 - mean_absolute_error: 187.7795 - val_loss: 53457.6914 - val_mean_absolute_error: 185.4059
Epoch 10/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 53076.2578 - mean_absolute_error: 184.2893 - val_loss: 50926.0625 - val_mean_absolute_error: 181.5532
Epoch 11/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - loss: 51132.9805 - mean_absolute_error: 181.2125 - val_loss: 49671.2773 - val_mean_absolute_error: 179.5928
Epoch 12/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 49823.7617 - mean_absolute_error: 178.7196 - val_loss: 48797.7383 - val_mean_absolute_error: 178.2561
Epoch 13/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 48821.1484 - mean_absolute_error: 177.6059 - val_loss: 48531.8242 - val_mean_absolute_error: 178.2161
Epoch 14/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 48148.4297 - mean_absolute_error: 175.9915 - val_loss: 47733.6562 - val_mean_absolute_error: 176.6568
Epoch 15/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - loss: 47572.6445 - mean_absolute_error: 174.6539 - val_loss: 47614.1914 - val_mean_absolute_error: 176.6535
Epoch 16/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 47145.6055 - mean_absolute_error: 173.9659 - val_loss: 47696.4961 - val_mean_absolute_error: 176.9848
Epoch 17/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - loss: 47419.8711 - mean_absolute_error: 174.8917 - val_loss: 47115.7891 - val_mean_absolute_error: 175.8477
Epoch 18/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 47271.4219 - mean_absolute_error: 174.3816 - val_loss: 46629.1367 - val_mean_absolute_error: 174.8154
Epoch 19/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - loss: 46496.6289 - mean_absolute_error: 173.1181 - val_loss: 46807.8828 - val_mean_absolute_error: 175.1853
Epoch 20/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - loss: 46572.2969 - mean_absolute_error: 172.5785 - val_loss: 46429.4180 - val_mean_absolute_error: 174.4833
Epoch 21/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 46461.7852 - mean_absolute_error: 172.8396 - val_loss: 46557.5195 - val_mean_absolute_error: 175.0003
Epoch 22/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 46388.0430 - mean_absolute_error: 173.0540 - val_loss: 46688.4180 - val_mean_absolute_error: 175.3220
Epoch 23/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 45847.3711 - mean_absolute_error: 171.5697 - val_loss: 46586.8789 - val_mean_absolute_error: 175.2351
Epoch 24/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 45815.2031 - mean_absolute_error: 172.1065 - val_loss: 46433.8672 - val_mean_absolute_error: 174.6571
Epoch 25/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - loss: 45573.3672 - mean_absolute_error: 171.3813 - val_loss: 46557.2734 - val_mean_absolute_error: 175.0316
Epoch 26/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - loss: 45565.1172 - mean_absolute_error: 170.9826 - val_loss: 46564.4023 - val_mean_absolute_error: 175.2030
Epoch 27/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 45387.0430 - mean_absolute_error: 170.8838 - val_loss: 46866.4961 - val_mean_absolute_error: 175.9624
Epoch 28/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 45173.8594 - mean_absolute_error: 169.8499 - val_loss: 46382.3867 - val_mean_absolute_error: 174.6706
Epoch 29/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 45430.0273 - mean_absolute_error: 170.6147 - val_loss: 46574.7617 - val_mean_absolute_error: 175.2966
Epoch 30/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 45274.7852 - mean_absolute_error: 170.3883 - val_loss: 46735.2031 - val_mean_absolute_error: 175.6862
Epoch 31/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 44713.8398 - mean_absolute_error: 169.5828 - val_loss: 46306.1719 - val_mean_absolute_error: 174.5270
Epoch 32/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - loss: 44932.8555 - mean_absolute_error: 169.9538 - val_loss: 46436.3906 - val_mean_absolute_error: 174.9372
Epoch 33/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 44757.7070 - mean_absolute_error: 169.4306 - val_loss: 46220.2617 - val_mean_absolute_error: 174.4529
Epoch 34/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 44841.8438 - mean_absolute_error: 169.8699 - val_loss: 46353.4062 - val_mean_absolute_error: 174.6017
Epoch 35/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - loss: 44794.7305 - mean_absolute_error: 169.5403 - val_loss: 46847.0391 - val_mean_absolute_error: 175.5162
Epoch 36/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - loss: 44758.3125 - mean_absolute_error: 169.4416 - val_loss: 46415.4688 - val_mean_absolute_error: 174.8846
Epoch 37/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 44339.6797 - mean_absolute_error: 168.8218 - val_loss: 46434.8789 - val_mean_absolute_error: 174.8939
Epoch 38/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 44733.3320 - mean_absolute_error: 169.3263 - val_loss: 46373.5977 - val_mean_absolute_error: 174.8195
Epoch 39/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - loss: 44267.6055 - mean_absolute_error: 168.8261 - val_loss: 46156.8594 - val_mean_absolute_error: 174.3624
Epoch 40/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 43938.0781 - mean_absolute_error: 167.7039 - val_loss: 46521.2852 - val_mean_absolute_error: 174.9607
Epoch 41/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - loss: 44383.3438 - mean_absolute_error: 168.8734 - val_loss: 46087.7188 - val_mean_absolute_error: 174.0789
Epoch 42/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 44349.7305 - mean_absolute_error: 168.7212 - val_loss: 46988.6953 - val_mean_absolute_error: 175.9890
Epoch 43/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 44566.2109 - mean_absolute_error: 169.0644 - val_loss: 46272.7070 - val_mean_absolute_error: 174.2142
Epoch 44/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 43762.5312 - mean_absolute_error: 167.2792 - val_loss: 46311.2109 - val_mean_absolute_error: 174.6214
Epoch 45/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 44018.3945 - mean_absolute_error: 168.0158 - val_loss: 46310.2930 - val_mean_absolute_error: 174.4977
Epoch 46/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - loss: 44303.9102 - mean_absolute_error: 168.6720 - val_loss: 46475.1367 - val_mean_absolute_error: 174.7988
Epoch 47/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - loss: 44125.4961 - mean_absolute_error: 167.6959 - val_loss: 46643.5508 - val_mean_absolute_error: 175.2251
Epoch 48/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - loss: 44209.4023 - mean_absolute_error: 168.3543 - val_loss: 46707.2656 - val_mean_absolute_error: 175.2233
Epoch 49/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 44115.1758 - mean_absolute_error: 168.5739 - val_loss: 47113.9336 - val_mean_absolute_error: 176.3147
Epoch 50/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 43718.2578 - mean_absolute_error: 167.4513 - val_loss: 46292.4531 - val_mean_absolute_error: 174.6097
Epoch 51/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 43843.0352 - mean_absolute_error: 167.7133 - val_loss: 46519.1094 - val_mean_absolute_error: 174.9369
Epoch 52/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 44051.8008 - mean_absolute_error: 168.0110 - val_loss: 46280.7148 - val_mean_absolute_error: 174.4002
Epoch 53/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 43673.3711 - mean_absolute_error: 167.2763 - val_loss: 46137.1523 - val_mean_absolute_error: 174.1379
Epoch 54/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - loss: 43755.1875 - mean_absolute_error: 167.4258 - val_loss: 46308.8203 - val_mean_absolute_error: 174.3302
Epoch 55/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 43194.3477 - mean_absolute_error: 166.5781 - val_loss: 46497.0391 - val_mean_absolute_error: 175.0334
Epoch 56/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 43565.3242 - mean_absolute_error: 166.8916 - val_loss: 46453.0820 - val_mean_absolute_error: 174.8857
Epoch 57/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 43137.6641 - mean_absolute_error: 166.5194 - val_loss: 46992.3594 - val_mean_absolute_error: 175.9635
Epoch 58/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 43634.0742 - mean_absolute_error: 167.4577 - val_loss: 46251.6172 - val_mean_absolute_error: 174.3516
Epoch 59/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 43129.2266 - mean_absolute_error: 166.5534 - val_loss: 45770.6250 - val_mean_absolute_error: 173.2561
Epoch 60/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 43276.2578 - mean_absolute_error: 166.5961 - val_loss: 46360.9492 - val_mean_absolute_error: 174.4616
Epoch 61/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 43418.2891 - mean_absolute_error: 166.4774 - val_loss: 46846.5312 - val_mean_absolute_error: 175.4658
Epoch 62/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 43210.0781 - mean_absolute_error: 166.2180 - val_loss: 46721.7695 - val_mean_absolute_error: 175.3133
Epoch 63/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - loss: 43092.7656 - mean_absolute_error: 165.9952 - val_loss: 45761.6406 - val_mean_absolute_error: 173.1880
Epoch 64/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 42861.5820 - mean_absolute_error: 165.5820 - val_loss: 46695.0664 - val_mean_absolute_error: 175.3281
Epoch 65/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 42931.0703 - mean_absolute_error: 165.5779 - val_loss: 45630.6680 - val_mean_absolute_error: 172.7086
Epoch 66/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 42845.0469 - mean_absolute_error: 165.2805 - val_loss: 46736.0703 - val_mean_absolute_error: 175.3909
Epoch 67/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 43452.6406 - mean_absolute_error: 166.3999 - val_loss: 46796.4492 - val_mean_absolute_error: 175.3754
Epoch 68/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 42850.6016 - mean_absolute_error: 165.4495 - val_loss: 46756.2422 - val_mean_absolute_error: 175.2031
Epoch 69/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 42775.7656 - mean_absolute_error: 164.9825 - val_loss: 46348.2070 - val_mean_absolute_error: 174.3626
Epoch 70/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 42882.6797 - mean_absolute_error: 166.1141 - val_loss: 45973.2930 - val_mean_absolute_error: 173.4050
Epoch 71/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 42814.7812 - mean_absolute_error: 165.3185 - val_loss: 46606.8281 - val_mean_absolute_error: 174.7641
Epoch 72/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 42508.3164 - mean_absolute_error: 164.8511 - val_loss: 46013.2734 - val_mean_absolute_error: 173.7330
Epoch 73/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 42527.3945 - mean_absolute_error: 164.4077 - val_loss: 46072.6172 - val_mean_absolute_error: 173.7755
Epoch 74/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 42569.6484 - mean_absolute_error: 164.5696 - val_loss: 46287.3867 - val_mean_absolute_error: 174.3352
Epoch 75/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 42250.0430 - mean_absolute_error: 164.6248 - val_loss: 45969.9336 - val_mean_absolute_error: 173.7117
Epoch 76/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - loss: 42806.9375 - mean_absolute_error: 165.6504 - val_loss: 45938.3281 - val_mean_absolute_error: 173.4554
Epoch 77/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 42296.5547 - mean_absolute_error: 164.6852 - val_loss: 46104.7227 - val_mean_absolute_error: 173.6570
Epoch 78/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 42274.5547 - mean_absolute_error: 164.0497 - val_loss: 46216.5078 - val_mean_absolute_error: 174.1013
Epoch 79/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 42643.1094 - mean_absolute_error: 164.9794 - val_loss: 46395.8164 - val_mean_absolute_error: 174.4785
Epoch 80/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 42349.4531 - mean_absolute_error: 164.4777 - val_loss: 46690.9102 - val_mean_absolute_error: 175.0923
Epoch 81/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 42357.8555 - mean_absolute_error: 164.1017 - val_loss: 46502.1094 - val_mean_absolute_error: 174.6612
Epoch 82/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 42001.1367 - mean_absolute_error: 163.9997 - val_loss: 46502.1250 - val_mean_absolute_error: 174.5540
Epoch 83/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - loss: 42227.1094 - mean_absolute_error: 164.4576 - val_loss: 46519.0234 - val_mean_absolute_error: 174.7761
Epoch 84/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 41916.5938 - mean_absolute_error: 163.6499 - val_loss: 46377.3711 - val_mean_absolute_error: 174.5102
Epoch 85/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 41971.1445 - mean_absolute_error: 163.8751 - val_loss: 46489.0859 - val_mean_absolute_error: 174.7499
Epoch 86/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 41954.1289 - mean_absolute_error: 163.7240 - val_loss: 45814.1094 - val_mean_absolute_error: 173.0374
Epoch 87/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 41831.5586 - mean_absolute_error: 162.9171 - val_loss: 46249.5977 - val_mean_absolute_error: 174.0190
Epoch 88/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 41919.8125 - mean_absolute_error: 163.3872 - val_loss: 46122.7500 - val_mean_absolute_error: 173.7173
Epoch 89/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 41977.5117 - mean_absolute_error: 163.2572 - val_loss: 46429.9805 - val_mean_absolute_error: 174.4740
Epoch 90/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 42105.5312 - mean_absolute_error: 163.7047 - val_loss: 46201.5742 - val_mean_absolute_error: 173.9379
Epoch 91/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 41721.5938 - mean_absolute_error: 163.1480 - val_loss: 46708.5898 - val_mean_absolute_error: 175.1022
Epoch 92/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 41273.7344 - mean_absolute_error: 162.3659 - val_loss: 46704.8867 - val_mean_absolute_error: 175.0924
Epoch 93/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - loss: 41609.6016 - mean_absolute_error: 162.6985 - val_loss: 46418.9297 - val_mean_absolute_error: 174.0948
Epoch 94/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 41782.0781 - mean_absolute_error: 163.1622 - val_loss: 46728.4180 - val_mean_absolute_error: 175.0268
Epoch 95/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - loss: 41305.1523 - mean_absolute_error: 162.0355 - val_loss: 46290.5859 - val_mean_absolute_error: 174.0493
Game ELO MAE:  172.05
Game ELO RMSE: 213.42

# Adding summary statistics to centipawn data

In [259]:
summary_data = neural_net_with_centipawn[neural_net_with_centipawn["total_turns"] >= 40].copy()
summary_data = summary_data[["white_centipawn", "black_centipawn", "white_elo", "black_elo", "index"]]

white_avg = []
white_std = []
white_median = []
white_max = []
white_min = []

black_avg = []
black_std = []
black_median = []
black_max = []
black_min = []

for idx, row in summary_data.iterrows():
    white_cp = row["white_centipawn"]
    white_avg.append(np.mean(white_cp))
    white_std.append(np.std(white_cp))
    white_median.append(np.median(white_cp))
    white_max.append(np.max(white_cp))
    white_min.append(np.min(white_cp))

    black_cp = row["black_centipawn"]
    black_avg.append(np.mean(black_cp))
    black_std.append(np.std(black_cp))
    black_median.append(np.median(black_cp))
    black_max.append(np.max(black_cp))
    black_min.append(np.min(black_cp))

summary_data["white_avg"] = white_avg
summary_data["white_std"] = white_std
summary_data["white_median"] = white_median
summary_data["white_max"] = white_max
summary_data["white_min"] = white_min

summary_data["black_avg"] = black_avg
summary_data["black_std"] = black_std
summary_data["black_median"] = black_median
summary_data["black_max"] = black_max
summary_data["black_min"] = black_min


summary_input = pd.concat(
    [
        white_cp_df,
        black_cp_df,
        summary_data[["white_avg", "white_std", "white_median", "white_max", "white_min", "black_avg", "black_std", "black_median", "black_max", "black_min"]]
    ],
    axis=1
)

summary_input["game_elo"] = (summary_data["white_elo"] + summary_data["black_elo"]) / 2

In [267]:
# ==============================
# Prepare summary data for dense neural net
# ==============================
summary_feature_cols = [col for col in summary_input.columns if col not in ["game_elo"]]
summary_target_cols = ["game_elo"]

X_summary = summary_input[summary_feature_cols].values.astype(np.float32)
y_summary = summary_input[summary_target_cols].values.astype(np.float32)

X_summary_train_full, X_summary_test, y_summary_train_full, y_summary_test = train_test_split(
    X_summary, y_summary, test_size=0.15, random_state=42
)

X_summary_train, X_summary_val, y_summary_train, y_summary_val = train_test_split(
    X_summary_train_full, y_summary_train_full, test_size=0.15, random_state=42
)

# ===================================
# Create normalization layer (scaling)
# ===================================
summary_normalizer = layers.Normalization(axis=-1)
summary_normalizer.adapt(X_summary_train)

# ==============================
# Build combined model
# ==============================
summary_model = keras.Sequential([
    keras.Input(shape=(X_summary_train.shape[1],)),
    summary_normalizer,
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(64, activation="relu"),
    layers.Dense(32, activation="relu"),
    layers.Dense(1)
])

summary_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="mse",
    metrics=[keras.metrics.MeanAbsoluteError()]
)

summary_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=15,
        restore_best_weights=True
    )
]

summary_history = summary_model.fit(
    X_summary_train, y_summary_train,
    validation_data=(X_summary_val, y_summary_val),
    epochs=200,
    batch_size=32,
    callbacks=summary_callbacks,
    verbose=1
)

# ==============================
# Evaluate
# ==============================
summary_pred = summary_model.predict(X_summary_test, verbose=0)

summary_game_mae = mean_absolute_error(y_summary_test[:, 0], summary_pred[:, 0])
summary_game_rmse = np.sqrt(mean_squared_error(y_summary_test[:, 0], summary_pred[:, 0]))

print(f"Game ELO MAE:  {summary_game_mae:.2f}")
print(f"Game ELO RMSE: {summary_game_rmse:.2f}")

# Save best-performing model
os.makedirs("weights", exist_ok=True)
summary_model.save("weights/flattened_centipawn_summary.keras")

Epoch 1/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 722us/step - loss: 1415256.3750 - mean_absolute_error: 1052.2020 - val_loss: 400750.8125 - val_mean_absolute_error: 519.8005
Epoch 2/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - loss: 184400.1406 - mean_absolute_error: 332.3985 - val_loss: 89594.9531 - val_mean_absolute_error: 234.9057
Epoch 3/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 92086.3203 - mean_absolute_error: 241.1132 - val_loss: 70652.8828 - val_mean_absolute_error: 211.3830
Epoch 4/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - loss: 79212.1797 - mean_absolute_error: 223.3206 - val_loss: 63537.4844 - val_mean_absolute_error: 201.4609
Epoch 5/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 71549.0000 - mean_absolute_error: 213.4410 - val_loss: 58598.4727 - val_mean_absolute_error: 194.2038
Epoch 6/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - loss: 65404.6953 - mean_absolute_error: 203.8358 - val_loss: 54274.0273 - val_mean_absolute_error: 186.4379
Epoch 7/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 61330.7070 - mean_absolute_error: 197.1610 - val_loss: 51587.0898 - val_mean_absolute_error: 182.1727
Epoch 8/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - loss: 58997.7773 - mean_absolute_error: 194.5370 - val_loss: 49553.2500 - val_mean_absolute_error: 178.2392
Epoch 9/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 56733.3828 - mean_absolute_error: 190.6477 - val_loss: 48633.9883 - val_mean_absolute_error: 176.3821
Epoch 10/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - loss: 54828.0742 - mean_absolute_error: 187.5423 - val_loss: 47142.0430 - val_mean_absolute_error: 173.9812
Epoch 11/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 53850.7109 - mean_absolute_error: 185.5776 - val_loss: 47232.2578 - val_mean_absolute_error: 174.1587
Epoch 12/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 52767.5586 - mean_absolute_error: 184.3158 - val_loss: 45632.1211 - val_mean_absolute_error: 171.3840
Epoch 13/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 52322.8555 - mean_absolute_error: 183.4096 - val_loss: 45709.3633 - val_mean_absolute_error: 171.5010
Epoch 14/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 51479.1953 - mean_absolute_error: 181.5634 - val_loss: 45132.3672 - val_mean_absolute_error: 170.6554
Epoch 15/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - loss: 51312.5938 - mean_absolute_error: 181.8616 - val_loss: 44993.4023 - val_mean_absolute_error: 170.4506
Epoch 16/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 50770.3750 - mean_absolute_error: 181.0344 - val_loss: 44949.1367 - val_mean_absolute_error: 170.3627
Epoch 17/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - loss: 51135.0977 - mean_absolute_error: 182.1504 - val_loss: 44211.0352 - val_mean_absolute_error: 168.7860
Epoch 18/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - loss: 50231.5078 - mean_absolute_error: 179.6866 - val_loss: 45611.5820 - val_mean_absolute_error: 171.7102
Epoch 19/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - loss: 50611.6484 - mean_absolute_error: 180.8100 - val_loss: 44772.4844 - val_mean_absolute_error: 169.7638
Epoch 20/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - loss: 49557.5898 - mean_absolute_error: 177.8714 - val_loss: 44404.0430 - val_mean_absolute_error: 169.1165
Epoch 21/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 49541.0977 - mean_absolute_error: 178.3239 - val_loss: 45328.7891 - val_mean_absolute_error: 170.9968
Epoch 22/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - loss: 49482.5742 - mean_absolute_error: 178.3927 - val_loss: 45298.0781 - val_mean_absolute_error: 170.8280
Epoch 23/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 49570.2969 - mean_absolute_error: 177.9701 - val_loss: 46588.5234 - val_mean_absolute_error: 173.9731
Epoch 24/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - loss: 49824.2891 - mean_absolute_error: 178.9830 - val_loss: 44234.7734 - val_mean_absolute_error: 168.7564
Epoch 25/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 49472.3945 - mean_absolute_error: 178.9794 - val_loss: 45291.7617 - val_mean_absolute_error: 170.9578
Epoch 26/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - loss: 48639.7539 - mean_absolute_error: 176.9991 - val_loss: 45914.4492 - val_mean_absolute_error: 172.3503
Epoch 27/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 48592.9492 - mean_absolute_error: 177.2082 - val_loss: 46309.9062 - val_mean_absolute_error: 173.1795
Epoch 28/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 48302.8984 - mean_absolute_error: 176.6303 - val_loss: 45111.5469 - val_mean_absolute_error: 170.7739
Epoch 29/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 47912.4688 - mean_absolute_error: 176.2599 - val_loss: 44053.4453 - val_mean_absolute_error: 168.5046
Epoch 30/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 48791.4062 - mean_absolute_error: 176.8669 - val_loss: 44387.3008 - val_mean_absolute_error: 169.0011
Epoch 31/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - loss: 48076.5312 - mean_absolute_error: 175.1610 - val_loss: 43871.9297 - val_mean_absolute_error: 168.0500
Epoch 32/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - loss: 48593.7070 - mean_absolute_error: 176.9925 - val_loss: 44216.2891 - val_mean_absolute_error: 168.8068
Epoch 33/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 47805.5625 - mean_absolute_error: 175.0109 - val_loss: 44031.4219 - val_mean_absolute_error: 168.2362
Epoch 34/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 48142.8945 - mean_absolute_error: 175.7968 - val_loss: 43788.0742 - val_mean_absolute_error: 168.1033
Epoch 35/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - loss: 47370.6797 - mean_absolute_error: 174.3408 - val_loss: 45206.4883 - val_mean_absolute_error: 171.3363
Epoch 36/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 47436.9180 - mean_absolute_error: 174.2859 - val_loss: 44391.7305 - val_mean_absolute_error: 169.5955
Epoch 37/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 47775.0234 - mean_absolute_error: 174.8624 - val_loss: 44840.4805 - val_mean_absolute_error: 169.8424
Epoch 38/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 47811.1641 - mean_absolute_error: 175.1609 - val_loss: 44928.2227 - val_mean_absolute_error: 170.5814
Epoch 39/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 48100.5273 - mean_absolute_error: 175.4056 - val_loss: 43988.7383 - val_mean_absolute_error: 168.4986
Epoch 40/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 47604.5273 - mean_absolute_error: 175.3605 - val_loss: 45182.0781 - val_mean_absolute_error: 170.7263
Epoch 41/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - loss: 47246.0742 - mean_absolute_error: 174.2151 - val_loss: 45336.4023 - val_mean_absolute_error: 171.5247
Epoch 42/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 46812.0742 - mean_absolute_error: 173.0614 - val_loss: 44121.6641 - val_mean_absolute_error: 168.3488
Epoch 43/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - loss: 47037.1719 - mean_absolute_error: 173.9569 - val_loss: 44842.3672 - val_mean_absolute_error: 170.6402
Epoch 44/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - loss: 46989.8945 - mean_absolute_error: 173.7694 - val_loss: 43507.4609 - val_mean_absolute_error: 166.6068
Epoch 45/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 46758.1289 - mean_absolute_error: 173.0113 - val_loss: 44360.4414 - val_mean_absolute_error: 169.1956
Epoch 46/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 46749.4492 - mean_absolute_error: 173.3914 - val_loss: 45266.8828 - val_mean_absolute_error: 171.2907
Epoch 47/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - loss: 46124.1406 - mean_absolute_error: 172.7195 - val_loss: 45359.1992 - val_mean_absolute_error: 171.2345
Epoch 48/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 46915.3828 - mean_absolute_error: 173.4437 - val_loss: 44182.6953 - val_mean_absolute_error: 168.1384
Epoch 49/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 46014.0234 - mean_absolute_error: 172.0784 - val_loss: 44505.7500 - val_mean_absolute_error: 169.7303
Epoch 50/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - loss: 46837.6211 - mean_absolute_error: 173.4367 - val_loss: 43859.1055 - val_mean_absolute_error: 168.0439
Epoch 51/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 45939.9492 - mean_absolute_error: 171.5941 - val_loss: 44620.6289 - val_mean_absolute_error: 169.7455
Epoch 52/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - loss: 45942.1797 - mean_absolute_error: 171.7652 - val_loss: 43718.0938 - val_mean_absolute_error: 167.7747
Epoch 53/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - loss: 46283.5781 - mean_absolute_error: 172.5809 - val_loss: 44228.8594 - val_mean_absolute_error: 168.9542
Epoch 54/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - loss: 46264.8555 - mean_absolute_error: 172.5273 - val_loss: 44720.6289 - val_mean_absolute_error: 170.4861
Epoch 55/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 46176.8125 - mean_absolute_error: 171.9232 - val_loss: 44942.7812 - val_mean_absolute_error: 170.5973
Epoch 56/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - loss: 45875.6562 - mean_absolute_error: 171.5675 - val_loss: 44304.5117 - val_mean_absolute_error: 169.2934
Epoch 57/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 45289.7383 - mean_absolute_error: 170.4298 - val_loss: 44159.6523 - val_mean_absolute_error: 169.1883
Epoch 58/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 45656.8633 - mean_absolute_error: 170.5341 - val_loss: 44763.8008 - val_mean_absolute_error: 170.4987
Epoch 59/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 45508.4453 - mean_absolute_error: 170.8643 - val_loss: 44586.9141 - val_mean_absolute_error: 170.0145
Game ELO MAE:  168.55
Game ELO RMSE: 209.53

# Combining the methods
- Take both strategy statistics and game evaluation to provide more accurate ELO prediction

In [261]:
combined_neural_net_input = pd.concat(
    [
        white_cp_df,
        black_cp_df,
        neural_net_with_centipawn[neural_net_with_centipawn["total_turns"] >= 40]
    ],
    axis=1
)

combined_neural_net_input["game_elo"] = combined_neural_net_input[["white_elo", "black_elo"]].mean(axis=1)
combined_neural_net_input = combined_neural_net_input.drop(columns=["centipawn", "black_centipawn", "white_centipawn", "idx", "index", "rating_bucket", "total_turns", "white_turns", "black_turns", "average_elo"])
combined_neural_net_input

,white_move_1,white_move_2,white_move_3,white_move_4,white_move_5,white_move_6,white_move_7,white_move_8,white_move_9,white_move_10,...,white_material_taken,white_material_lost,black_promotions,black_forced_moves,black_material_taken,black_material_lost,white_elo,black_elo,winner,game_elo
1,39,42,25,18,70,73,260,506,571,552,...,38,7,0,0,7,38,1496,1500,1.0,1498.0
2,43,37,48,0,89,133,172,232,382,437,...,30,8,0,0,8,30,1439,1454,1.0,1446.5
3,40,45,74,91,117,115,111,82,45,-75,...,38,30,0,1,30,38,1523,1469,1.0,1496.0
5,47,46,32,114,53,51,44,15,10,1,...,12,24,0,3,24,12,1439,1392,-1.0,1415.5
6,36,76,82,89,180,175,59,159,184,106,...,38,37,0,0,37,38,1381,1209,1.0,1295.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15934,41,60,40,85,54,51,19,39,-4,-74,...,15,20,0,0,20,15,1328,1252,1.0,1290.0
15936,43,59,38,7,-189,22,-271,-350,-159,-181,...,10,15,0,1,15,10,1237,1231,-1.0,1234.0
15939,43,64,132,111,8,23,15,18,21,-28,...,25,26,0,1,26,25,1233,1196,-1.0,1214.5
15941,42,61,66,-123,-121,-45,-62,-122,-154,-199,...,38,31,0,2,31,38,1360,1227,1.0,1293.5
15942,42,41,89,93,93,115,252,211,236,293,...,22,26,0,1,26,22,1235,1339,-1.0,1287.0

In [262]:
# ==============================
# Prepare combined data for dense neural net
# ==============================
combined_feature_cols = [col for col in combined_neural_net_input.columns if col not in ["white_elo", "black_elo", "game_elo"]]
combined_target_cols = ["game_elo"]

X_combined = combined_neural_net_input[combined_feature_cols].values.astype(np.float32)
y_combined = combined_neural_net_input[combined_target_cols].values.astype(np.float32)

X_combined_train_full, X_combined_test, y_combined_train_full, y_combined_test = train_test_split(
    X_combined, y_combined, test_size=0.15, random_state=42
)

X_combined_train, X_combined_val, y_combined_train, y_combined_val = train_test_split(
    X_combined_train_full, y_combined_train_full, test_size=0.15, random_state=42
)

# ===================================
# Create normalization layer (scaling)
# ===================================
combined_normalizer = layers.Normalization(axis=-1)
combined_normalizer.adapt(X_combined_train)

# ==============================
# Build combined model
# ==============================
combined_model = keras.Sequential([
    keras.Input(shape=(X_combined_train.shape[1],)),
    combined_normalizer,
    layers.Dense(256, activation="relu"),
    # layers.Dropout(0.2),
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(1)
])

combined_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    loss="mse",
    metrics=[keras.metrics.MeanAbsoluteError()]
)

combined_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=30,
        restore_best_weights=True
    )
]

combined_history = combined_model.fit(
    X_combined_train, y_combined_train,
    validation_data=(X_combined_val, y_combined_val),
    epochs=200,
    batch_size=32,
    callbacks=combined_callbacks,
    verbose=1
)

# ==============================
# Evaluate
# ==============================
combined_pred = combined_model.predict(X_combined_test, verbose=0)

combined_game_mae = mean_absolute_error(y_combined_test[:, 0], combined_pred[:, 0])
combined_game_rmse = np.sqrt(mean_squared_error(y_combined_test[:, 0], combined_pred[:, 0]))

print(f"Game ELO MAE:  {combined_game_mae:.2f}")
print(f"Game ELO RMSE: {combined_game_rmse:.2f}")

Epoch 1/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - loss: 1464557.7500 - mean_absolute_error: 1065.3337 - val_loss: 314714.4062 - val_mean_absolute_error: 448.7460
Epoch 2/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 202874.0312 - mean_absolute_error: 357.0383 - val_loss: 152840.8594 - val_mean_absolute_error: 302.8763
Epoch 3/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 123110.1328 - mean_absolute_error: 277.1586 - val_loss: 117953.6797 - val_mean_absolute_error: 264.6151
Epoch 4/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - loss: 99436.3594 - mean_absolute_error: 249.4286 - val_loss: 101532.3750 - val_mean_absolute_error: 245.3784
Epoch 5/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 86443.1406 - mean_absolute_error: 233.1993 - val_loss: 92093.7656 - val_mean_absolute_error: 233.8998
Epoch 6/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 77648.2969 - mean_absolute_error: 221.6138 - val_loss: 85715.2969 - val_mean_absolute_error: 225.8239
Epoch 7/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 71090.0078 - mean_absolute_error: 212.5995 - val_loss: 81098.4453 - val_mean_absolute_error: 219.6078
Epoch 8/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 65947.8750 - mean_absolute_error: 205.1363 - val_loss: 77519.2031 - val_mean_absolute_error: 214.7789
Epoch 9/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 61768.1094 - mean_absolute_error: 198.7784 - val_loss: 74652.4062 - val_mean_absolute_error: 211.0999
Epoch 10/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 58326.3320 - mean_absolute_error: 193.2480 - val_loss: 72329.1562 - val_mean_absolute_error: 208.1763
Epoch 11/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 55406.5430 - mean_absolute_error: 188.3928 - val_loss: 70328.3516 - val_mean_absolute_error: 205.6155
Epoch 12/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 52907.2383 - mean_absolute_error: 184.1317 - val_loss: 68661.8984 - val_mean_absolute_error: 203.4426
Epoch 13/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 50751.5977 - mean_absolute_error: 180.3533 - val_loss: 67241.2500 - val_mean_absolute_error: 201.5375
Epoch 14/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 48875.2656 - mean_absolute_error: 176.9793 - val_loss: 65991.2266 - val_mean_absolute_error: 199.7965
Epoch 15/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - loss: 47226.1055 - mean_absolute_error: 173.9577 - val_loss: 64936.6797 - val_mean_absolute_error: 198.3339
Epoch 16/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 45761.2539 - mean_absolute_error: 171.2092 - val_loss: 64047.3828 - val_mean_absolute_error: 197.1147
Epoch 17/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 44453.4492 - mean_absolute_error: 168.7262 - val_loss: 63221.6016 - val_mean_absolute_error: 195.9743
Epoch 18/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 43268.4688 - mean_absolute_error: 166.4464 - val_loss: 62526.0859 - val_mean_absolute_error: 195.0261
Epoch 19/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 42196.3008 - mean_absolute_error: 164.3488 - val_loss: 61955.1875 - val_mean_absolute_error: 194.1881
Epoch 20/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 41222.0664 - mean_absolute_error: 162.4134 - val_loss: 61424.2578 - val_mean_absolute_error: 193.3915
Epoch 21/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 40316.2539 - mean_absolute_error: 160.5865 - val_loss: 60936.0117 - val_mean_absolute_error: 192.6671
Epoch 22/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - loss: 39478.8320 - mean_absolute_error: 158.8713 - val_loss: 60516.8945 - val_mean_absolute_error: 192.0283
Epoch 23/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 38667.8750 - mean_absolute_error: 157.2006 - val_loss: 60110.7500 - val_mean_absolute_error: 191.4242
Epoch 24/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 37887.9141 - mean_absolute_error: 155.5678 - val_loss: 59677.4062 - val_mean_absolute_error: 190.7677
Epoch 25/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 37112.6133 - mean_absolute_error: 153.9330 - val_loss: 59281.8750 - val_mean_absolute_error: 190.2034
Epoch 26/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 36349.0781 - mean_absolute_error: 152.2882 - val_loss: 58935.1250 - val_mean_absolute_error: 189.6873
Epoch 27/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 35604.0938 - mean_absolute_error: 150.6669 - val_loss: 58624.6367 - val_mean_absolute_error: 189.2380
Epoch 28/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - loss: 34895.4727 - mean_absolute_error: 149.0996 - val_loss: 58319.1953 - val_mean_absolute_error: 188.7596
Epoch 29/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 34219.2734 - mean_absolute_error: 147.5906 - val_loss: 58052.0469 - val_mean_absolute_error: 188.3637
Epoch 30/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 33563.4609 - mean_absolute_error: 146.0951 - val_loss: 57858.0625 - val_mean_absolute_error: 188.0310
Epoch 31/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 32933.3633 - mean_absolute_error: 144.6253 - val_loss: 57677.0977 - val_mean_absolute_error: 187.7418
Epoch 32/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 32324.6367 - mean_absolute_error: 143.1910 - val_loss: 57574.3750 - val_mean_absolute_error: 187.5839
Epoch 33/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 31725.5254 - mean_absolute_error: 141.7604 - val_loss: 57476.1523 - val_mean_absolute_error: 187.3745
Epoch 34/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 31144.5762 - mean_absolute_error: 140.3605 - val_loss: 57441.4336 - val_mean_absolute_error: 187.2970
Epoch 35/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - loss: 30566.5059 - mean_absolute_error: 138.9462 - val_loss: 57423.6211 - val_mean_absolute_error: 187.2044
Epoch 36/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 29995.1328 - mean_absolute_error: 137.5209 - val_loss: 57435.1562 - val_mean_absolute_error: 187.1747
Epoch 37/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 29446.7832 - mean_absolute_error: 136.1633 - val_loss: 57469.1523 - val_mean_absolute_error: 187.1652
Epoch 38/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - loss: 28900.6074 - mean_absolute_error: 134.7869 - val_loss: 57508.9805 - val_mean_absolute_error: 187.1716
Epoch 39/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 28360.0469 - mean_absolute_error: 133.4067 - val_loss: 57565.4648 - val_mean_absolute_error: 187.2365
Epoch 40/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - loss: 27821.4902 - mean_absolute_error: 132.0301 - val_loss: 57637.6641 - val_mean_absolute_error: 187.3168
Epoch 41/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 27294.9180 - mean_absolute_error: 130.6689 - val_loss: 57761.6289 - val_mean_absolute_error: 187.4726
Epoch 42/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 26768.7988 - mean_absolute_error: 129.2916 - val_loss: 57909.0977 - val_mean_absolute_error: 187.6688
Epoch 43/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 26240.2852 - mean_absolute_error: 127.9006 - val_loss: 58063.6250 - val_mean_absolute_error: 187.9196
Epoch 44/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 25717.1367 - mean_absolute_error: 126.5146 - val_loss: 58219.5000 - val_mean_absolute_error: 188.1134
Epoch 45/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 25198.1348 - mean_absolute_error: 125.1193 - val_loss: 58416.4688 - val_mean_absolute_error: 188.3987
Epoch 46/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 24682.9141 - mean_absolute_error: 123.7151 - val_loss: 58568.2422 - val_mean_absolute_error: 188.6515
Epoch 47/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 24167.8613 - mean_absolute_error: 122.2567 - val_loss: 58781.1211 - val_mean_absolute_error: 188.9792
Epoch 48/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 23653.5898 - mean_absolute_error: 120.7924 - val_loss: 59002.4805 - val_mean_absolute_error: 189.3100
Epoch 49/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 23145.7617 - mean_absolute_error: 119.3322 - val_loss: 59224.6133 - val_mean_absolute_error: 189.6531
Epoch 50/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 22651.3477 - mean_absolute_error: 117.9221 - val_loss: 59482.5703 - val_mean_absolute_error: 190.0520
Epoch 51/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 22154.5215 - mean_absolute_error: 116.4885 - val_loss: 59778.7305 - val_mean_absolute_error: 190.5005
Epoch 52/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 21657.6270 - mean_absolute_error: 115.0053 - val_loss: 60075.6211 - val_mean_absolute_error: 191.0005
Epoch 53/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 21167.0469 - mean_absolute_error: 113.5390 - val_loss: 60376.6016 - val_mean_absolute_error: 191.5217
Epoch 54/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 20684.3398 - mean_absolute_error: 112.0854 - val_loss: 60637.7109 - val_mean_absolute_error: 191.9855
Epoch 55/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 20204.7246 - mean_absolute_error: 110.6337 - val_loss: 60967.1562 - val_mean_absolute_error: 192.4837
Epoch 56/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - loss: 19726.8555 - mean_absolute_error: 109.1513 - val_loss: 61299.9688 - val_mean_absolute_error: 193.0347
Epoch 57/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 19246.4863 - mean_absolute_error: 107.6415 - val_loss: 61624.7070 - val_mean_absolute_error: 193.5711
Epoch 58/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 18779.1855 - mean_absolute_error: 106.1434 - val_loss: 61912.8438 - val_mean_absolute_error: 194.0666
Epoch 59/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 18312.2559 - mean_absolute_error: 104.6555 - val_loss: 62195.8516 - val_mean_absolute_error: 194.4611
Epoch 60/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 17855.5039 - mean_absolute_error: 103.1602 - val_loss: 62586.4258 - val_mean_absolute_error: 195.0730
Epoch 61/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - loss: 17394.4277 - mean_absolute_error: 101.6354 - val_loss: 62950.7773 - val_mean_absolute_error: 195.6236
Epoch 62/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 16942.3809 - mean_absolute_error: 100.1463 - val_loss: 63288.7422 - val_mean_absolute_error: 196.1366
Epoch 63/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 16496.2539 - mean_absolute_error: 98.6721 - val_loss: 63611.5156 - val_mean_absolute_error: 196.6124
Epoch 64/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 16056.1973 - mean_absolute_error: 97.2074 - val_loss: 63995.3086 - val_mean_absolute_error: 197.1579
Epoch 65/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 15624.5938 - mean_absolute_error: 95.7534 - val_loss: 64416.7812 - val_mean_absolute_error: 197.7774
Game ELO MAE:  186.51
Game ELO RMSE: 235.90

In [263]:
# ==============================
# Baseline comparison: predict mean game ELO
# ==============================
baseline_mean_pred = np.full((len(y_combined_test), 1), y_combined_train_full.mean())

baseline_game_mae = mean_absolute_error(y_combined_test[:, 0], baseline_mean_pred[:, 0])
baseline_game_rmse = np.sqrt(mean_squared_error(y_combined_test[:, 0], baseline_mean_pred[:, 0]))

comparison_df = pd.DataFrame(
    {
        "model": ["Mean baseline", "Combined neural net"],
        "game_mae": [baseline_game_mae, combined_game_mae],
        "game_rmse": [baseline_game_rmse, combined_game_rmse],
    }
)

print("Improvement over mean baseline (positive is better):")
print(f"Game ELO MAE improvement:  {baseline_game_mae - combined_game_mae:.2f}")
print(f"Game ELO RMSE improvement: {baseline_game_rmse - combined_game_rmse:.2f}")

comparison_df

Improvement over mean baseline (positive is better):
Game ELO MAE improvement:  21.09
Game ELO RMSE improvement: 20.45

                 model    game_mae   game_rmse
0        Mean baseline  207.597778  256.346979
1  Combined neural net  186.511200  235.895750

# Strategy Board Statistics + Centipawn Summary Statistics Model

In [264]:
# ==============================
# Combine board strategy stats with centipawn summary stats
# ==============================
board_strategy_cols = [
    col for col in neural_net_input.columns
    if col not in ["white_elo", "black_elo", "game_elo", "winner", "total_turns", "white_turns", "black_turns", "idx", "average_elo", "rating_bucket"]
]

centipawn_summary_cols = [
    "white_avg", "white_std", "white_median", "white_max", "white_min",
    "black_avg", "black_std", "black_median", "black_max", "black_min"
]

strategy_summary_input = pd.concat(
    [
        neural_net_with_centipawn.loc[summary_data.index, board_strategy_cols].reset_index(drop=True),
        summary_data[centipawn_summary_cols].reset_index(drop=True)
    ],
    axis=1
)

strategy_summary_input["game_elo"] = (
    summary_data["white_elo"].reset_index(drop=True) +
    summary_data["black_elo"].reset_index(drop=True)
) / 2

# ==============================
# Prepare data for dense neural net
# ==============================
strategy_summary_feature_cols = [col for col in strategy_summary_input.columns if col != "game_elo"]
strategy_summary_target_cols = ["game_elo"]

X_strategy_summary = strategy_summary_input[strategy_summary_feature_cols].values.astype(np.float32)
y_strategy_summary = strategy_summary_input[strategy_summary_target_cols].values.astype(np.float32)

X_strategy_summary_train_full, X_strategy_summary_test, y_strategy_summary_train_full, y_strategy_summary_test = train_test_split(
    X_strategy_summary, y_strategy_summary, test_size=0.15, random_state=42
)

X_strategy_summary_train, X_strategy_summary_val, y_strategy_summary_train, y_strategy_summary_val = train_test_split(
    X_strategy_summary_train_full, y_strategy_summary_train_full, test_size=0.15, random_state=42
)

# ===================================
# Create normalization layer (scaling)
# ===================================
strategy_summary_normalizer = layers.Normalization(axis=-1)
strategy_summary_normalizer.adapt(X_strategy_summary_train)

# ==============================
# Build model
# ==============================
strategy_summary_model = keras.Sequential([
    keras.Input(shape=(X_strategy_summary_train.shape[1],)),
    strategy_summary_normalizer,
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(1)
])

strategy_summary_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="mse",
    metrics=[keras.metrics.MeanAbsoluteError()]
)

strategy_summary_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=15,
        restore_best_weights=True
    )
]

strategy_summary_history = strategy_summary_model.fit(
    X_strategy_summary_train, y_strategy_summary_train,
    validation_data=(X_strategy_summary_val, y_strategy_summary_val),
    epochs=200,
    batch_size=32,
    callbacks=strategy_summary_callbacks,
    verbose=1
)

# ==============================
# Evaluate
# ==============================
strategy_summary_pred = strategy_summary_model.predict(X_strategy_summary_test, verbose=0)

strategy_summary_mae = mean_absolute_error(y_strategy_summary_test[:, 0], strategy_summary_pred[:, 0])
strategy_summary_rmse = np.sqrt(mean_squared_error(y_strategy_summary_test[:, 0], strategy_summary_pred[:, 0]))

print(f"Game ELO MAE:  {strategy_summary_mae:.2f}")
print(f"Game ELO RMSE: {strategy_summary_rmse:.2f}")

Epoch 1/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - loss: 674653.8750 - mean_absolute_error: 603.6559 - val_loss: 116429.9688 - val_mean_absolute_error: 263.6765
Epoch 2/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - loss: 100306.4922 - mean_absolute_error: 249.8323 - val_loss: 91377.7578 - val_mean_absolute_error: 234.1760
Epoch 3/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 83032.9688 - mean_absolute_error: 228.7443 - val_loss: 80817.3281 - val_mean_absolute_error: 220.8622
Epoch 4/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 73339.5469 - mean_absolute_error: 215.6395 - val_loss: 74727.5078 - val_mean_absolute_error: 212.5519
Epoch 5/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 66062.0000 - mean_absolute_error: 204.9029 - val_loss: 71468.1250 - val_mean_absolute_error: 208.3394
Epoch 6/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - loss: 62140.2266 - mean_absolute_error: 198.8329 - val_loss: 68449.5938 - val_mean_absolute_error: 204.5295
Epoch 7/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 59671.9141 - mean_absolute_error: 195.5186 - val_loss: 68807.5625 - val_mean_absolute_error: 205.3192
Epoch 8/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 57197.3672 - mean_absolute_error: 190.9715 - val_loss: 66173.0625 - val_mean_absolute_error: 201.7364
Epoch 9/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 55583.1484 - mean_absolute_error: 187.9334 - val_loss: 65372.9609 - val_mean_absolute_error: 200.8949
Epoch 10/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 53261.9180 - mean_absolute_error: 185.0334 - val_loss: 64591.1523 - val_mean_absolute_error: 199.3531
Epoch 11/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - loss: 53237.8047 - mean_absolute_error: 184.1293 - val_loss: 63100.3789 - val_mean_absolute_error: 196.3979
Epoch 12/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 51381.7461 - mean_absolute_error: 180.7724 - val_loss: 62896.9609 - val_mean_absolute_error: 196.8208
Epoch 13/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 50467.0469 - mean_absolute_error: 179.3394 - val_loss: 63957.9766 - val_mean_absolute_error: 198.6736
Epoch 14/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 50193.9414 - mean_absolute_error: 178.9313 - val_loss: 64367.8750 - val_mean_absolute_error: 199.8110
Epoch 15/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - loss: 49344.2578 - mean_absolute_error: 176.9591 - val_loss: 60988.1797 - val_mean_absolute_error: 194.2192
Epoch 16/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 47540.4531 - mean_absolute_error: 174.5302 - val_loss: 61872.7695 - val_mean_absolute_error: 195.2907
Epoch 17/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 47326.8672 - mean_absolute_error: 174.2673 - val_loss: 61593.7695 - val_mean_absolute_error: 194.3823
Epoch 18/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - loss: 47304.1953 - mean_absolute_error: 173.7376 - val_loss: 62671.9141 - val_mean_absolute_error: 197.0029
Epoch 19/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - loss: 46552.8711 - mean_absolute_error: 172.0716 - val_loss: 62499.1562 - val_mean_absolute_error: 195.6778
Epoch 20/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 46471.6641 - mean_absolute_error: 172.2298 - val_loss: 60746.2188 - val_mean_absolute_error: 193.6708
Epoch 21/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 45064.7930 - mean_absolute_error: 169.5747 - val_loss: 61063.0625 - val_mean_absolute_error: 194.3453
Epoch 22/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 45048.3008 - mean_absolute_error: 168.7871 - val_loss: 61174.4727 - val_mean_absolute_error: 193.9581
Epoch 23/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 44077.0742 - mean_absolute_error: 167.5128 - val_loss: 64054.2773 - val_mean_absolute_error: 197.9100
Epoch 24/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 44033.1523 - mean_absolute_error: 167.3146 - val_loss: 60467.3828 - val_mean_absolute_error: 193.1851
Epoch 25/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - loss: 43526.7227 - mean_absolute_error: 166.4818 - val_loss: 64203.7266 - val_mean_absolute_error: 198.0434
Epoch 26/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - loss: 43271.1523 - mean_absolute_error: 165.9507 - val_loss: 59157.4336 - val_mean_absolute_error: 191.3962
Epoch 27/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - loss: 42694.8594 - mean_absolute_error: 164.4784 - val_loss: 60073.5820 - val_mean_absolute_error: 192.3143
Epoch 28/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 42664.6172 - mean_absolute_error: 164.6621 - val_loss: 60752.6172 - val_mean_absolute_error: 193.1848
Epoch 29/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 41772.9297 - mean_absolute_error: 162.7219 - val_loss: 60878.9297 - val_mean_absolute_error: 193.7013
Epoch 30/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 41334.4688 - mean_absolute_error: 162.1311 - val_loss: 61136.9336 - val_mean_absolute_error: 194.0549
Epoch 31/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 40874.5469 - mean_absolute_error: 161.6635 - val_loss: 59511.6211 - val_mean_absolute_error: 191.0816
Epoch 32/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - loss: 40162.2188 - mean_absolute_error: 159.5760 - val_loss: 61783.9688 - val_mean_absolute_error: 193.3260
Epoch 33/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 39556.3398 - mean_absolute_error: 158.1545 - val_loss: 60969.1445 - val_mean_absolute_error: 192.0260
Epoch 34/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 40379.0742 - mean_absolute_error: 160.3167 - val_loss: 61864.9609 - val_mean_absolute_error: 194.4139
Epoch 35/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 39425.9766 - mean_absolute_error: 158.9136 - val_loss: 59290.6445 - val_mean_absolute_error: 189.9429
Epoch 36/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 38809.1289 - mean_absolute_error: 156.9765 - val_loss: 60709.1484 - val_mean_absolute_error: 192.6997
Epoch 37/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 38074.3906 - mean_absolute_error: 154.7688 - val_loss: 61510.6250 - val_mean_absolute_error: 193.7726
Epoch 38/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 38119.0703 - mean_absolute_error: 154.9847 - val_loss: 62376.6992 - val_mean_absolute_error: 193.5641
Epoch 39/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - loss: 37689.9844 - mean_absolute_error: 154.0299 - val_loss: 60569.7617 - val_mean_absolute_error: 191.7563
Epoch 40/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 36787.7695 - mean_absolute_error: 152.3390 - val_loss: 62383.9375 - val_mean_absolute_error: 194.1871
Epoch 41/200
269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 36595.6328 - mean_absolute_error: 152.6235 - val_loss: 61774.8086 - val_mean_absolute_error: 193.5591
Game ELO MAE:  187.60
Game ELO RMSE: 238.10